[tool.poetry]
name = "savantpy"
version = "0.1.0"
description = ""
authors = ["jc.durbin <jc.durbin@ardanis.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.2"
chromadb = "^0.3.23"
langchain = "^0.0.173"
yachalk = "^0.1.5"
openai = "^0.27.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
